# Generated by Django 3.2.9 on 2021-12-09 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('month_spendings', '0002_spendcategory_is_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
